name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_brain_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_brain_db
      PGPASSWORD: postgres

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Reset database
        run: |
          psql -h localhost -U postgres -d postgres -c "
            SELECT pg_terminate_backend(pg_stat_activity.pid)
            FROM pg_stat_activity
            WHERE pg_stat_activity.datname = 'test_brain_db'
              AND pid <> pg_backend_pid();
          "
          psql -h localhost -U postgres -d postgres -c "DROP DATABASE IF EXISTS test_brain_db;"
          psql -h localhost -U postgres -d postgres -c "CREATE DATABASE test_brain_db;"

      - name: Run migrations
        run: yarn typeorm migration:run

      - name: Run tests
        run: yarn test
